# src/main/resources/application.yml
server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=OrderMS;encrypt=false;integratedSecurity=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database: SQL_SERVER
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
        temp.use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true

  sql:
    init:
      mode: never




logging:
  level:
    com.smartpfa: DEBUG
    org.springframework.kafka: DEBUG

